'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useAccount,usePublicClient,useSwitchChain,useWalletClient} from 'wagmi';
import {formatUnits,parseUnits,type Address,type PublicClient,type WalletClient} from 'viem';
import {DeltaVaultClient,parseDeployment,marketId,type Action,type Deployment} from '@/lib/onchain/client';
import {Btn,Tag} from '../ui';
import Link from '../site-link';
type Snapshot=Awaited<ReturnType<DeltaVaultClient['snapshot']>>;
type Position=Awaited<ReturnType<DeltaVaultClient['position']>>;
const units=(v?:bigint)=>v===undefined?'—':Number(formatUnits(v,6)).toLocaleString(undefined,{maximumFractionDigits:6});
const fail=(e:unknown)=>e instanceof Error?e.message:'The request failed';
export default function OnchainTerminal({section='all',initialMarket='BTC-USD'}:{section?:'all'|'trade'|'vaults'|'portfolio';initialMarket?:'BTC-USD'|'ETH-USD'}){
 const {address,isConnected,chainId}=useAccount();const {switchChain,isPending:switching}=useSwitchChain();
 const [deployment,setDeployment]=useState<Deployment>();const [configError,setConfigError]=useState('');const [loadingConfig,setLoadingConfig]=useState(true);
 const [marketName,setMarketName]=useState(initialMarket);const [amount,setAmount]=useState('100');const [burn,setBurn]=useState('100');const [lev,setLev]=useState(2);const [positionId,setPositionId]=useState('');
 const [history,setHistory]=useState<Awaited<ReturnType<DeltaVaultClient['recentPositions']>>>([]);const [historyError,setHistoryError]=useState('');const [snapshot,setSnapshot]=useState<Snapshot>();const [position,setPosition]=useState<Position>();const [readError,setReadError]=useState('');const [error,setError]=useState('');const [status,setStatus]=useState('');const [hash,setHash]=useState<`0x${string}`>();const [busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const abort=new AbortController();fetch('/deltavault-deployment.json',{signal:abort.signal,cache:'no-store'}).then(async r=>{if(r.status===404){setConfigError('Contract deployment is not configured yet.');return}if(!r.ok)throw Error('Unable to load contract deployment');setDeployment(parseDeployment(await r.json()))}).catch(e=>{if(!abort.signal.aborted)setConfigError(fail(e))}).finally(()=>{if(!abort.signal.aborted)setLoadingConfig(false)});return()=>abort.abort()},[]);
 const publicClient=usePublicClient({chainId:deployment?.chainId??46630});const {data:wallet}=useWalletClient();
 const client=useMemo(()=>deployment&&publicClient?new DeltaVaultClient(deployment,publicClient as PublicClient,wallet as WalletClient|undefined):undefined,[deployment,publicClient,wallet]);
 const id=marketId(marketName);const pid=/^[1-9]\d*$/.test(positionId)?BigInt(positionId):undefined;
 const ready=!!client&&isConnected&&chainId===deployment?.chainId;
 // A generation counter discards results from a previous account, market, or position.
 const generation=useRef(0);
 const refresh=useCallback(async()=>{
  const version=++generation.current;if(!ready||!client||!address)return;
  try{const [s,p]=await Promise.all([client.snapshot(id,address),pid?client.position(pid):Promise.resolve(undefined)]);if(version===generation.current){setSnapshot(s);setPosition(p);setReadError('')}}catch(e){if(version===generation.current)setReadError(fail(e))}
 },[ready,client,address,id,pid]);
 useEffect(()=>{setSnapshot(undefined);setPosition(undefined);setReadError('');setHash(undefined);setStatus('');setError('')},[address,id,chainId]);
 useEffect(()=>{setPosition(undefined)},[pid]);
 useEffect(()=>{void refresh();const interval=setInterval(()=>void refresh(),10000);return()=>{generation.current++;clearInterval(interval)}},[refresh]);
 function amountRaw(value:string){if(!/^\d+(\.\d{1,6})?$/.test(value))return undefined;const n=parseUnits(value,6);return n>0n&&n<=parseUnits('1000000',6)?n:undefined}
 const raw=amountRaw(amount),burned=amountRaw(burn);const needsApproval=raw!==undefined&&(snapshot?.allowance??0n)<raw;
 const owns=position?.position[0].toLowerCase()===address?.toLowerCase();const active=!!position?.position[6];
 const enabled=ready&&!busy&&!readError&&!!snapshot;
 async function execute(action:Action,args:readonly unknown[]){
  if(lock.current||!client||!address)return;lock.current=true;setBusy(true);setError('');setHash(undefined);setStatus('Checking transaction…');
  try{const result=await client.transact(action,address,args,(phase,tx)=>{if(tx)setHash(tx);setStatus(phase==='signature'?'Approve this transaction in your wallet.':phase==='submitted'?'Transaction submitted. Waiting for confirmation…':'Transaction confirmed.');});if(result.openedId!==undefined)setPositionId(result.openedId.toString());await refresh()}catch(e){setError(fail(e));setStatus('Action did not complete.')}finally{lock.current=false;setBusy(false)}
 }
 useEffect(()=>{let cancelled=false;setHistory([]);setHistoryError('');if(ready&&client&&address&&section==='portfolio')client.recentPositions(address).then(rows=>{if(!cancelled)setHistory(rows)}).catch(e=>{if(!cancelled)setHistoryError(fail(e))});return()=>{cancelled=true}},[ready,client,address,section,status]);
 const showVault=section!=='trade',showTrade=section!=='vaults';
 return <div className="wrap onchain-page"><div className="page-head"><div><span className="eyebrow">CONTRACT EXECUTION / TEST ASSETS</span><h1>{section==='vaults'?'Your market vault.':section==='portfolio'?'Your onchain balances.':'Trade on testnet.'}</h1><p>Market-specific liquidity and bounded long or short positions using test dvUSD.</p></div><Tag tone="amber">Test assets only</Tag></div>
 <p className="notice">Test prices are controlled by the deployer. These contracts use different rules from the simulated demo: 1–5× leverage, no trading fees, and liquidation at 80% collateral loss.</p>
 {loadingConfig?<p role="status">Loading deployment…</p>:!deployment?<section className="panel onchain-card"><h2>Contracts are not deployed here yet</h2><p>{configError}</p><p>Explore the simulated demo above, or follow the repository setup guide to deploy and connect the test contracts.</p><a className="text-link" href="https://github.com/anon-coder-88/delta-vault" target="_blank" rel="noopener noreferrer">Open source and setup guide</a></section>:!isConnected?<section className="panel onchain-card"><h2>Connect a wallet</h2><p>Choose Connect Wallet in the navbar to read your balances and use the contracts.</p></section>:chainId!==deployment.chainId?<section className="panel onchain-card"><h2>Switch network</h2><p>This deployment uses {deployment.chainId===31337?'your local development chain':'Robinhood Chain testnet'}.</p><Btn disabled={switching} onClick={()=>switchChain({chainId:deployment.chainId})}>{switching?'Switching…':'Switch network'}</Btn></section>:<>
 {section==='portfolio'&&<section className="panel onchain-card"><h2>Your recent positions</h2><p className="meta">Your positions among the latest 30 protocol positions. Enter an older position ID below to inspect it.</p>{history.length?history.map(row=><div className="kv" key={row.id.toString()}><span>#{row.id.toString()} · {row.position[5]?'Long':'Short'} · {row.position[6]?'Active':'Settled'}</span><Btn secondary disabled={busy} onClick={()=>setPositionId(row.id.toString())}>Inspect position</Btn></div>):<p>No positions found in this recent window.</p>}{historyError&&<p className="error" role="alert">Position history unavailable: {historyError}</p>}</section>}
 <div className="onchain-grid"><section className="panel onchain-card"><h2>Market and balances</h2><label htmlFor="contract-market">Market</label><select id="contract-market" disabled={busy} value={marketName} onChange={e=>setMarketName(e.target.value as typeof marketName)}><option>BTC-USD</option><option>ETH-USD</option></select><div className="kv"><span>Test price</span><strong>{snapshot?Number(formatUnits(snapshot.market[3],8)).toLocaleString():'—'} USD</strong></div><div className="kv"><span>Wallet collateral</span><strong>{units(snapshot?.balance)} dvUSD</strong></div><div className="kv"><span>Market liquidity</span><strong>{units(snapshot?.market[0])} dvUSD</strong></div><div className="kv"><span>Available withdrawal liquidity</span><strong>{units(snapshot?.available)} dvUSD</strong></div><div className="kv"><span>Available trading capacity</span><strong>{units(snapshot?.capacity)} dvUSD</strong></div><div className="kv"><span>Your shares</span><strong>{units(snapshot?.shares)}</strong></div><div className="kv"><span>Your share value</span><strong>{units(snapshot?.shareValue)} dvUSD</strong></div><p className="meta">Price updated {snapshot?.market[4]?new Date(Number(snapshot.market[4])*1000).toLocaleString():'—'}. {!snapshot?.fresh?'A fresh price is needed for trades and settlement.':''} {snapshot?.paused?'New deposits and positions are paused.':''}</p><Btn secondary disabled={busy} onClick={()=>void refresh()}>Refresh balances</Btn></section>
 <section className="panel onchain-card"><h2>Test collateral</h2><label htmlFor="contract-amount">Collateral amount · dvUSD</label><input id="contract-amount" disabled={busy} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/>{raw===undefined&&<p className="error">Enter 0.000001–1,000,000 with at most six decimal places.</p>}<div className="onchain-actions"><Btn secondary disabled={!enabled} onClick={()=>void execute('faucet',[])}>Claim test dvUSD</Btn><Btn secondary disabled={!enabled||raw===undefined} onClick={()=>void execute('approve',[deployment.vault,raw!])}>Approve amount</Btn>{showVault&&<Btn disabled={!enabled||!raw||needsApproval||snapshot?.paused||!snapshot?.market[5]||(snapshot?.balance??0n)<raw} onClick={()=>void execute('deposit',[id,raw!])}>Deposit liquidity</Btn>}</div><p className="meta">Approval and deposit or position opening are separate transactions. The faucet can be claimed once per address and does not provide gas.</p></section>
 {showVault&&<section className="panel onchain-card"><h2>Withdraw liquidity</h2><label htmlFor="contract-shares">Shares to redeem · 6 decimals</label><input id="contract-shares" disabled={busy} inputMode="decimal" value={burn} onChange={e=>setBurn(e.target.value)}/><p className="meta">Estimated return: {burned&&snapshot?.market[1]?units(burned*snapshot.market[0]/snapshot.market[1]):'—'} dvUSD. Reserved liquidity cannot be withdrawn.</p><Btn secondary disabled={!enabled||!burned||burned>(snapshot?.shares??0n)} onClick={()=>void execute('withdraw',[id,burned!])}>Withdraw shares</Btn></section>}
 {showTrade&&<section className="panel onchain-card"><h2>Open a position</h2><label htmlFor="contract-leverage">Leverage · {lev}×</label><input id="contract-leverage" disabled={busy} type="range" min="1" max="5" value={lev} onChange={e=>setLev(Number(e.target.value))}/><p className="meta">Exposure: {raw?units(raw*BigInt(lev)):'—'} dvUSD. Profit is capped at exposure; loss is capped at collateral.</p><div className="onchain-actions">{[true,false].map(long=><Btn key={String(long)} secondary={!long} disabled={!enabled||!raw||needsApproval||!snapshot?.fresh||snapshot?.paused||!snapshot?.market[5]||(snapshot?.balance??0n)<raw||raw*BigInt(lev)>(snapshot?.capacity??0n)} onClick={()=>void execute('openPosition',[id,raw!,lev,long])}>Open {long?'long':'short'}</Btn>)}</div>{needsApproval&&<p className="meta">Approve the collateral amount first.</p>}</section>}
 {showTrade&&<section className="panel onchain-card"><h2>Position settlement</h2><label htmlFor="contract-position">Position ID</label><input id="contract-position" disabled={busy} inputMode="numeric" value={positionId} onChange={e=>setPositionId(e.target.value)}/>{position&&<><p>{active?`${position.position[5]?'Long':'Short'} · ${owns?'Your position':'Another wallet’s position'}`:'No active position at this ID'}</p>{active&&<><div className="kv"><span>Collateral</span><strong>{units(position.position[2])} dvUSD</strong></div><div className="kv"><span>Current PnL</span><strong>{units(position.pnl)} dvUSD</strong></div><div className="kv"><span>Estimated payout</span><strong>{units(position.payout)} dvUSD</strong></div></>}</>}<div className="onchain-actions"><Btn disabled={!enabled||!pid||!active||!owns} onClick={()=>void execute('closePosition',[pid!])}>Close position</Btn><Btn secondary disabled={!enabled||!pid||!position?.liquidatable} onClick={()=>void execute('liquidate',[pid!])}>Liquidate unhealthy position</Btn></div><p className="meta">Settlement requires a fresh price for the position’s market. Anyone can liquidate an eligible position; its remaining collateral returns to the trader.</p></section>}
 </div>{readError&&<p className="error" role="alert">Contract reads unavailable: {readError}</p>}{status&&<p className="notice" role="status">{status}</p>}{error&&<p className="error" role="alert">{error}</p>}{hash&&<p className="meta">Transaction: {deployment.chainId===46630?<a href={`https://explorer.testnet.chain.robinhood.com/tx/${hash}`} target="_blank" rel="noopener noreferrer">{hash.slice(0,14)}…</a>:hash}</p>}
 </>}<p className="meta"><Link href="/risk">Read the risk disclosures</Link> · Demo holdings and contract balances are separate.</p></div>;
}
