'use client';
import {useEffect,useRef,useState,useMemo} from 'react';
import {useQuery} from '@tanstack/react-query';
import {getCandles,getQuote,sampleSeries,Range,RANGES} from '@/lib/deltavault/data';
import {getMarket,MarketId} from '@/lib/deltavault/engine';
import {Btn,Tag,usd} from './ui';
export default function PriceChart({marketId}:{marketId:MarketId}){const m=getMarket(marketId)!;const [range,setRange]=useState<Range>('1D');const [now,setNow]=useState(()=>Date.now());const [renderError,setRenderError]=useState(false);const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(t)},[]);
const quote=useQuery({queryKey:['quote',m.pair],queryFn:({signal})=>getQuote(m.pair,signal),refetchInterval:q=>q.state.error?false:30000,refetchIntervalInBackground:false});
const candles=useQuery({queryKey:['candles',m.pair,range],queryFn:({signal})=>getCandles(m.pair,range,signal),staleTime:300000});const fallback=useMemo(()=>sampleSeries(Number(m.price),range),[m.price,range]);const data=candles.data?.length?candles.data:fallback;const isSample=!candles.data?.length;const stale=quote.data&&now-Date.parse(quote.data.time)>90000;
useEffect(()=>{let cancelled=false;let cleanup=()=>{};import('lightweight-charts').then(({createChart,AreaSeries,ColorType})=>{if(cancelled||!ref.current)return;setRenderError(false);const el=ref.current;const chart=createChart(el,{autoSize:true,height:320,layout:{background:{type:ColorType.Solid,color:'#0b1d2a'},textColor:'#AFBFCA',fontFamily:'Inter, sans-serif',fontSize:12,attributionLogo:true},grid:{vertLines:{color:'#17303d'},horzLines:{color:'#17303d'}},rightPriceScale:{borderColor:'#29424f'},timeScale:{borderColor:'#29424f',timeVisible:true},crosshair:{vertLine:{color:'#67E8DC',labelBackgroundColor:'#285064'},horzLine:{color:'#67E8DC',labelBackgroundColor:'#285064'}}});const series=chart.addSeries(AreaSeries,{lineColor:'#67E8DC',topColor:'rgba(103,232,220,.19)',bottomColor:'rgba(103,232,220,0)',lineWidth:2,priceLineVisible:false});series.setData(data as Parameters<typeof series.setData>[0]);chart.timeScale().fitContent();cleanup=()=>chart.remove()}).catch(()=>setRenderError(true));return()=>{cancelled=true;cleanup()}},[data,marketId,range]);
const vals=data.flatMap(d=>'value' in d?[d.value]:[]),low=Math.min(...vals),high=Math.max(...vals);return <div className="chart-panel"><div className="chart-head"><div><span className="meta">{m.pair} · external reference</span><div className="reference-value">{quote.data?usd(quote.data.price):<span className="unavailable">{quote.isPending?'Reading reference…':'Reference unavailable'}</span>}{quote.data&&<Tag tone={stale?'amber':'cyan'}>{stale?'Stale':'Coinbase'}</Tag>}</div><span className="meta">{quote.data?`${new Date(quote.data.time).toLocaleString()} · local time · not a settlement oracle`:'Scenario execution price is shown in the order ticket.'}</span></div><div className="chart-ranges" aria-label="Chart time range">{(Object.keys(RANGES) as Range[]).map(r=><Btn secondary key={r} aria-pressed={range===r} className={range===r?'selected':''} onClick={()=>setRange(r)}>{r}</Btn>)}</div></div><div className="chart-source"><Tag tone={isSample?'amber':'cyan'}>{isSample?'Sample data':'Coinbase reference'}</Tag><span>{isSample?(candles.isPending?'Loading historical reference data…':'Reference source unavailable. Showing a labeled sample series.'):(candles.isError?'Last available reference series. Refresh failed.':'Historical spot prices · independent of demo execution')}</span>{(quote.isError||candles.isError)&&<button className="text-link" onClick={()=>{quote.refetch();candles.refetch()}}>Retry source</button>}</div><div ref={ref} className="price-chart" role="img" aria-label={`${m.name} ${range} chart. ${isSample?'Sample data':'Coinbase reference'}. Lowest price ${usd(low)}, highest ${usd(high)}.`}>{renderError&&<div className="empty"><p>Chart rendering is unavailable. Price summary remains below.</p></div>}</div><div className="chart-summary"><span>{isSample?'Sample':'Reference'} range: {usd(low)} – {usd(high)}</span><a href="https://www.tradingview.com/lightweight-charts/" target="_blank" rel="noreferrer">Charts by TradingView</a></div></div>}
