'use client';
import Link from '@/components/deltavault/site-link';
import {lazy,Suspense,useState,useEffect,useCallback} from 'react';
import {Layers3,SlidersHorizontal,Activity,ShieldCheck,MoveUpRight,Orbit} from 'lucide-react';
import {ActionLink,Coin,Tag,compact,usd} from './ui';
import {MARKETS,vaultMetrics} from '@/lib/deltavault/engine';
import {useDemo} from './providers';
import HomeMotion from './home-motion';
const Aperture=lazy(()=>import('./aperture'));
export default function Home(){const {state}=useDemo();const [mount,setMount]=useState(false),[ready,setReady]=useState(false);const onReady=useCallback(()=>setReady(true),[]);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{setMount(!media.matches);if(media.matches)setReady(false)};const frame=requestAnimationFrame(sync);media.addEventListener('change',sync);return()=>{cancelAnimationFrame(frame);media.removeEventListener('change',sync)}},[]);return <><HomeMotion/><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/>BUILT AROUND YOUR MARKET</div><h1><span className="hero-line"><span>Capital in motion.</span></span>{' '}<span className="hero-line accent"><span>Risk in focus.</span></span></h1><p>Explore a different angle on trading and liquidity. Dedicated market vaults. Defined exposure. Everything in view.</p><div className="hero-actions"><ActionLink href="/trade">Explore trading demo</ActionLink><ActionLink href="/vaults" secondary>Explore vaults</ActionLink></div><div className="hero-note"><span className="outline-dot"/>An interactive demo. No wallet required.</div></div><div className="hero-art"><div className="art-grid"/><span className="object-label top">DV / APERTURE 01</span><div className="object-stage"><img className={`object-poster ${ready?'loaded':''}`} src="/brand/aperture.svg" alt="Three layered DeltaVault apertures represent separate market vaults" width="600" height="600"/>{mount&&<Suspense fallback={null}><Aperture onReady={onReady}/></Suspense>}</div><div className="art-caption"><span>ONE MARKET.<br/><strong>ITS OWN FOUNDATION.</strong></span><span className="coordinate">Δ / 03</span></div></div><div className="hero-bottom"><span>TRADING & LIQUIDITY INFRASTRUCTURE</span><span>ON ROBINHOOD CHAIN</span><span className="scroll-label">SCROLL TO EXPLORE</span></div></section>
<section className="market-overview"><div className="wrap"><div className="section-top"><div><span className="eyebrow">EXPLORE THE ENVIRONMENT</span><h2>Your market.<br/>Your perspective.</h2></div><p>Two illustrative markets to explore how positions and vault liquidity fit together.</p></div><div className="market-label"><Tag>Illustrative markets</Tag><span>Prices and liquidity below are sample scenario values.</span></div><div className="market-rows">{MARKETS.map(m=>{const v=vaultMetrics(state,m.id);return <Link className="market-row" key={m.id} href={`/trade?market=${m.id}`}><div className="market-identity"><Coin id={m.id} size={49}/><div><strong>{m.name}</strong><span>{m.pair}</span></div></div><div><span>Scenario price</span><strong>{usd(state.prices[m.id])}</strong></div><div><span>Sample liquidity</span><strong>{compact(v.total.toString())}</strong></div><div><span>Demo leverage</span><strong>Up to {m.maxLeverage}×</strong></div><span className="row-link">Explore market</span></Link>})}</div></div></section>
<section className="system-section wrap"><div className="section-top"><div><span className="eyebrow">A MORE FOCUSED STRUCTURE</span><h2>One market.<br/><span className="muted">Its own foundation.</span></h2></div><p>Each market has a dedicated vault. Understand where liquidity sits, how exposure is bounded, and what that means for you.</p></div><div className="system-grid"><article className="feature-major"><div className="feature-heading"><Layers3/><span>01 / MARKET VAULTS</span></div><h3>Liquidity with<br/>a defined role.</h3><p>Explore separate capital pools built around the needs of each market.</p><div className="liquidity-diagram" aria-label="Each market is connected to its own separate vault"><div><Coin id="btc"/><span>BTC market</span><div className="diagram-track"/><Layers3 size={25}/><span>BTC vault</span></div><div><Coin id="eth"/><span>ETH market</span><div className="diagram-track alt"/><Layers3 size={25}/><span>ETH vault</span></div></div><Link className="text-link" href="/vaults">Understand market vaults</Link></article><div className="feature-stack"><article><SlidersHorizontal/><div><span className="eyebrow">02 / CONFIGURABLE EXPOSURE</span><h3>Find your position.</h3><p>Rehearse long and short positions with adjustable collateral and leverage. Review the risk before every action.</p><Link className="text-link" href="/trade">Try the trading demo</Link></div></article><article><Activity/><div><span className="eyebrow">03 / VISIBLE ASSUMPTIONS</span><h3>Know what you’re looking at.</h3><p>Reference prices, sample data and simulated results are clearly labeled, from market view to portfolio.</p><Link className="text-link" href="/docs">Explore the protocol model</Link></div></article></div></div></section>
<section className="risk-section"><div className="wrap risk-layout"><div><span className="eyebrow">CLARITY COMES FIRST</span><h2>Understand the risk.<br/><span className="muted">Then take a position.</span></h2><p>Leverage can amplify losses. Vault liquidity can be constrained. Explore the mechanics before putting capital at risk.</p><ActionLink href="/risk" secondary>Read the risk guide</ActionLink></div><div className="risk-index">{[['01','Leverage & liquidation','How a price move can affect your collateral.'],['02','Liquidity & capacity','Why market limits and available liquidity matter.'],['03','Oracles & contracts','The dependencies behind protocol execution.']].map(([num,title,copy])=><Link key={num} href="/risk"><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></Link>)}</div></div></section>
<section className="final-cta wrap"><img src="/brand/symbol.svg" width="44" height="44" alt=""/><h2>See the model in motion.</h2><p>Start with 10,000 simulated USD. Explore at your own pace.</p><ActionLink href="/trade">Enter the demo</ActionLink><span>Simulated funds · Device-local portfolio · No transaction signatures</span></section></>}
