'use client';
import Link from '@/components/deltavault/site-link';
import {usePathname} from 'next/navigation';
import {ReactNode,useState,useEffect} from 'react';
import {Menu} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import WalletButton from './wallet';
import {Btn} from './ui';
import PageCurtain from './page-curtain';
const NAV=[['Trade','/trade'],['Vaults','/vaults'],['Portfolio','/portfolio'],['Tokenomics','/token'],['Docs','/docs']];
export default function Shell({children}:{children:ReactNode}){const path=usePathname();const [menu,setMenu]=useState(false);return <><PageCurtain/><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><div className="header-inner"><Link href="/" className="logo-link" aria-label="DeltaVault home"><img src="/brand/logo.svg" alt="DeltaVault" width="182" height="38"/></Link><nav className="desktop-nav" aria-label="Main navigation">{NAV.map(([label,url])=><Link key={url} href={url} className={path.startsWith(url)?'active':''} aria-current={path.startsWith(url)?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><WalletButton/><Dialog open={menu} onOpenChange={setMenu}><DialogTrigger asChild><Btn secondary className="menu-toggle" aria-label="Open navigation"><Menu/></Btn></DialogTrigger><DialogContent className="dv-dialog"><DialogTitle>Explore DeltaVault</DialogTitle><DialogDescription>Trading, liquidity and protocol resources.</DialogDescription><nav className="mobile-nav" aria-label="Mobile navigation">{[['Home','/'],...NAV,['Risk','/risk']].map(([label,url])=><Link key={url} href={url} onClick={()=>setMenu(false)}>{label}</Link>)}</nav></DialogContent></Dialog></div></div></header><main id="main" key={path} className={`route-enter ${path==='/'?'home-main':'app-main'}`}>{children}</main><footer className="site-footer"><div className="footer-top"><div><Link href="/" className="logo-link"><img src="/brand/logo.svg" alt="DeltaVault" width="182" height="38"/></Link><p>Market-specific liquidity.<br/>A clearer view of risk.</p></div><div><h3>Explore</h3><Link href="/trade">Trading demo</Link><Link href="/vaults">Market vaults</Link><Link href="/portfolio">Your portfolio</Link></div><div><h3>Understand</h3><Link href="/docs">Documentation</Link><Link href="/token">Tokenomics</Link><Link href="/risk">Risk disclosures</Link></div><div className="footer-status"><span className="eyebrow">CURRENT ENVIRONMENT</span><p>Interactive demo</p><span>Wallet reads: Robinhood Testnet</span></div></div><div className="footer-bottom"><span>© 2026 DeltaVault</span><p>Independent third-party project. No Robinhood endorsement. Leveraged trading and liquidity provision involve risk of loss.</p></div></footer></>}
