'use client';
import Link from '@/components/deltavault/site-link';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ReactNode,useState,useRef} from 'react';
import {Review,MARKETS,MarketId} from '@/lib/deltavault/engine';
import {useDemo} from './providers';
import {FlaskConical,Layers3} from 'lucide-react';
export function Btn({children,className='',secondary=false,...props}:React.ComponentProps<typeof Button>&{secondary?:boolean}){return <Button {...props} className={`dv-button ${secondary?'secondary':''} ${className}`}>{children}</Button>}
export function ActionLink({href,children,secondary=false,className=''}:{href:string;children:ReactNode;secondary?:boolean;className?:string}){return <Button asChild className={`dv-button ${secondary?'secondary':''} ${className}`}><Link href={href}>{children}</Link></Button>}
export const usd=(v:string|number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v));
export const compact=(v:string|number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(Number(v));
export function Coin({id,size=40}:{id:MarketId;size?:number}){const m=MARKETS.find(x=>x.id===id)!;return <span className={`coin coin-${id}`} style={{width:size,height:size,color:m.color}} aria-hidden="true">{id==='btc'?'₿':'Ξ'}</span>}
export function Tag({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`tag ${tone}`}>{children}</span>}
export function Metric({label,value,note,positive=false}:{label:string;value:ReactNode;note?:string;positive?:boolean}){return <div className="metric"><span>{label}</span><strong className={positive?'positive':''}>{value}</strong>{note&&<small>{note}</small>}</div>}
export function PageHead({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{children}</div>}
export function DemoBanner(){const {notice}=useDemo();return <><div className="demo-banner"><FlaskConical size={16}/><p><strong>Demo environment</strong><span> Practice with simulated USD. No real trades or deposits.</span></p><Link href="/docs#demo-rules">How it works</Link></div>{notice&&<div className="notice" role="status">{notice} <Link href="/portfolio">Manage demo</Link></div>}</>}
export function Empty({title,body,children}:{title:string;body:string;children?:ReactNode}){return <div className="empty"><Layers3 size={30}/><h3>{title}</h3><p>{body}</p>{children}</div>}
export function ReviewModal({review,onClose}:{review:Review|null;onClose:()=>void}){const {state,confirm}=useDemo();const returnFocus=useRef<HTMLElement|null>(null);const [error,setError]=useState(''),[busy,setBusy]=useState(false);const stale=!!review&&review.revision!==state.revision;return <Dialog open={!!review} onOpenChange={v=>{if(!v){setError('');onClose()}}}><DialogContent className="dv-dialog" onOpenAutoFocus={()=>{returnFocus.current=document.activeElement as HTMLElement}} onCloseAutoFocus={e=>{e.preventDefault();if(returnFocus.current?.isConnected)returnFocus.current.focus();else document.getElementById('review-action')?.focus()}}><DialogTitle className="dialog-heading">{review?.title}</DialogTitle><DialogDescription>Demo only. Confirming changes your local simulated portfolio.</DialogDescription><div className="review-items">{review?.items.map(([k,v])=><div className="kv" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="risk-note">{review?.risk} <Link href="/risk" onClick={onClose}>Read the risks</Link></p>{(error||stale)&&<p role="alert" className="error">{stale?'The scenario or balance changed. Close this review and review again.':error}</p>}<div className="dialog-actions"><Btn secondary onClick={()=>{setError('');onClose()}}>Cancel</Btn><Btn disabled={busy||stale} onClick={()=>{if(!review||busy)return;setBusy(true);try{confirm(review);setError('');onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Confirm simulation</Btn></div></DialogContent></Dialog>}
