import {readFile, writeFile} from 'node:fs/promises';

const contracts = ['MarketVault', 'DevelopmentAsset', 'DevelopmentPriceSource'];
let module = '// Generated by scripts/abi.mjs from solc 0.8.30 Foundry artifacts. Do not edit.\n';
for (const name of contracts) {
  const artifact = JSON.parse(await readFile(`out/${name}.sol/${name}.json`, 'utf8'));
  module += `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
await writeFile('packages/abi/index.ts', module);
